version: '3.7'
services:
  mysqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
  ontrackrxapi:
    user: root
    build: ./
    ports:
      - "5001:80"
    depends_on:
      - mysqlserver
      