using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OntrackDb.Migrations
{
    public partial class MedicationConditionValuesAdded : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
                            migrationBuilder.InsertData(
                      table: "medicationCondition",
                      columns: new[] { "name" },
                      values: new object[,]
                      {
                            {   "Aneurysm" },
                            {   "Acid reflux" },
                            {   "Acne" },
                            {   "Alcohol/drug dependency" },
                            {   "Allergic rhinitis" },
                            {   "Allergies" },
                            {   "Alzheimer's disease" },
                            {   "Anaphylaxis" },
                            {   "Anemia" },
                            {   "Angina" },
                            {   "Angioedema" },
                            {   "Anorexia" },
                            {   "Anxiety" },
                            {   "Appendicitis" },
                            {   "Arrhythmias" },
                            {   "Arthritis" },
                            {   "Asthma" },
                            {   "Atrial fibrillation" },
                            {   "Attention deficit hyperactivity disorder (ADHD)" },
                            {   "Autoimmune disorder" },
                            {   "Bacterial infection" },
                            {   "Benign prostate enlargement" },
                            {   "Bipolar disorder" },
                            {   "Bladder cancer" },
                            {   "Bladder control" },
                            {   "Blood clot prevention" },
                            {   "Blood disorder" },
                            {   "Bowel incontinence" },
                            {   "Brain tumours" },
                            {   "Breast cancer" },
                            {   "Bronchitis" },
                            {   "Cancer" },
                            {   "Cardiovascular disease" },
                            {   "Cervical cancer" },
                            {   "Chest infection" },
                            {   "Chest pain" },
                            {   "Chickenpox" },
                            {   "Chilblains" },
                            {   "Chlamydia" },
                            {   "Chronic kidney disease" },
                            {   "Chronic obstructive pulmonary disease (COPD)" },
                            {   "Chronic pain" },
                            {   "Chronic pancreatitis" },
                            {   "Cirrhosis" },
                            {   "Cold sore" },
                            { "Common cold" },
                            { "Common heart conditions" },
                            { "Conjunctivitis" },
                            { "Constipation" },
                            { "Coronavirus (COVID-19)" },
                            { "Cough" },
                            { "Crohn's disease" },
                            { "Cystic fibrosis" },
                            { "Deep vein thrombosis" },
                            { "Dehydration" },
                            { "Dementia" },
                            { "Depression" },
                            { "Dermatitis" },
                            { "Diabetes" },
                            { "Diarrhea" },
                            { "Digestive disorder" },
                            { "Dizziness" },
                            { "Dry mouth" },
                            { "Dysphagia (swallowing problems)" },
                            { "Ear infection" },
                            { "Earache" },
                            { "Earwax build-up" },
                            { "Eating disorders" },
                            { "Eczema" },
                            { "End stage liver disease" },
                            { "End stage renal disease" },
                            { "Endometriosis" },
                            { "Enlarged prostate" },
                            { "Epilepsy" },
                            { "Erectile dysfunction (impotence)" },
                            { "Eye cancer" },
                            { "Eye condition" },
                            { "Fever" },
                            { "Fibroids" },
                            { "Fibromyalgia" },
                            { "Fluid retention" },
                            { "Food poisoning" },
                            { "Fungal nail infection" },
                            { "Gallbladder cancer" },
                            { "Gallstones" },
                            { "Gas" },
                            { "Gastro-esophageal reflux disease (GERD)" },
                            { "Gastroenteritis" },
                            { "General health" },
                            { "Genetic conditions" },
                            { "Genital herpes" },
                            { "Genital symptoms" },
                            { "Genital warts" },
                            { "Glaucoma" },
                            { "Gonorrhoea" },
                            { "Gout" },
                            { "Gum disease" },
                            { "Hand, foot and mouth disease" },
                            { "Hay fever" },
                            { "Head and neck cancer" },
                            { "Head lice and nits" },
                            { "Headache" },
                            { "Hearing loss" },
                            { "Heart disease" },
                            { "Heart Event" },
                            { "Heart failure" },
                            { "Heartburn" },
                            { "Hemorrhoids" },
                            { "Hepatitis" },
                            { "High Blood Pressure" },
                            { "High cholesterol" },
                            { "HIV/AIDS" },
                            { "Hodgkin lymphoma" },
                            { "Hormone replacement therapy (HRT)" },
                            { "Huntington's disease" },
                            { "Hyperglycaemia (high blood sugar)" },
                            { "Hyperthyroidism (overactive thyroid)" },
                            { "Hypoglycaemia (low blood sugar)" },
                            { "Hypothyroidism (underactive thyroid)" },
                            { "Immunization" },
                            { "Indigestion" },
                            { "Infection" },
                            { "Inflammatory bowel disease (IBD)" },
                            { "Influenza (flu)" },
                            { "Insomnia" },
                            { "Iron deficiency anaemia" },
                            { "Irritable bowel syndrome (IBS)" },
                            { "Itching" },
                            { "Kidney cancer" },
                            { "Kidney infection" },
                            { "Kidney stones" },
                            { "Lactose intolerance" },
                            { "Leg cramps" },
                            { "Leukaemia" },
                            { "Lice" },
                            { "Liver cancer" },
                            { "Liver disease" },
                            { "Lung cancer" },
                            { "Lung disease" },
                            { "Lupus" },
                            { "Lyme disease" },
                            { "Malaria" },
                            { "Malignant brain tumour (cancerous)" },
                            { "Malnutrition" },
                            { "Measles" },
                            { "Memory disorder" },
                            { "Meningitis" },
                            { "Menopause" },
                            { "Mental health condition" },
                            { "Migraine" },
                            { "Mood disorder" },
                            { "Morning sickness" },
                            { "Mouth cancer" },
                            { "Mouth ulcer" },
                            { "Movement disorder" },
                            { "Multiple myeloma" },
                            { "Multiple sclerosis (MS)" },
                            { "Mumps" },
                            { "Myasthenia gravis" },
                            { "Nausea" },
                            { "Nerve pain" },
                            { "Neurological Condition" },
                            { "Non-Hodgkin lymphoma" },
                            { "Nosebleed" },
                            { "Obesity" },
                            { "Obsessive compulsive disorder (OCD)" },
                            { "Obstructive sleep apnoea" },
                            { "Osteoporosis" },
                            { "Otitis externa" },
                            { "Ovarian cancer" },
                            { "Ovarian cyst" },
                            { "Pain" },
                            { "Pancreatic cancer" },
                            { "Pancreatitis" },
                            { "Panic disorder" },
                            { "Parkinson's disease" },
                            { "Pelvic inflammatory disease" },
                            { "Peripheral neuropathy" },
                            { "Peripheral vascular disease" },
                            { "Personality disorder" },
                            { "Post-traumatic stress disorder (PTSD)" },
                            { "Pregnancy" },
                            { "Pressure ulcers" },
                            { "Prostate cancer" },
                            { "Psoriasis" },
                            { "Psoriatic arthritis" },
                            { "Psychosis" },
                            { "Restless legs syndrome" },
                            { "Rheumatoid arthritis" },
                            { "Ringworm and other fungal infections" },
                            { "Rosacea" },
                            { "Scabies" },
                            { "Schizophrenia" },
                            { "Seizures" },
                            { "Sexual dysfunction" },
                            { "Sexually transmitted infections (STIs)" },
                            { "Shingles" },
                            { "Shortness of breath" },
                            { "Sickle cell disease" },
                            { "Sinusitis" },
                            { "Skin cancer" },
                            { "Skin condition" },
                            { "Sleep disorder" },
                            { "Sore throat" },
                            { "Staph (Staphylococcus aureus)" },
                            {"Stomach ache and abdominal pain" },
                            { "Stomach cancer" },
                            { "Stomach ulcer" },
                            { "Stress" },
                            { "Stroke" },
                            { "Sunburn" },
                            { "Syphilis" },
                            { "Testicular cancer" },
                            { "Thrush" },
                            { "Thyroid cancer" },
                            { "Thyroid disorder" },
                            { "Tinnitus" },
                            { "Tobacco cessation" },
                            { "Tonsillitis" },
                             {  "Tooth decay" },
                            { "Toothache" },
                            { "Transient ischaemic attack (TIA)" },
                            { "Type 1 diabetes" },
                            { "Type 2 diabetes" },
                            { "Ulcerative colitis" },
                            { "Urinary incontinence" },
                            { "Urinary tract infection (UTI)" },
                            { "Urticaria (hives)" },
                            { "Vaginal discharge" },
                            { "Vertigo" },
                            { "Viruse Infection" },
                            { "Vitamin B12 or folate deficiency anaemia" },
                            { "Vomiting" },
                            { "Warts" },
                            { "Weight loss" },
                            { "Weight management" },
                            { "Wheezing" },
                            { "Whooping cough" },
                      });
                   }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
                        migrationBuilder.InsertData(
                    table: "medicationCondition",
                    column: "name",
                    values: new[]
                                {
                                    "Aneurysm",
                                    "Acid reflux",
                                    "Acne",
                                    "Alcohol/drug dependency" ,
                                    "Allergic rhinitis" ,
                                    "Allergies" ,
                                    "Alzheimer's disease" ,
                                    "Anaphylaxis",
                                    "Anemia" ,
                                    "Angina" ,
                                    "Angioedema" ,
                                    "Anorexia",
                                    "Anxiety",
                                    "Appendicitis" ,
                                    "Arrhythmias" ,
                                    "Arthritis" ,
                                    "Asthma" ,
                                    "Atrial fibrillation" ,
                                    "Attention deficit hyperactivity disorder (ADHD)" ,
                                    "Autoimmune disorder" ,
                                    "Bacterial infection" ,
                                    "Benign prostate enlargement" ,
                                    "Bipolar disorder" ,
                                    "Bladder cancer" ,
                                    "Bladder control" ,
                                    "Blood clot prevention" ,
                                    "Blood disorder" ,
                                    "Bowel incontinence" ,
                                    "Brain tumours" ,
                                    "Breast cancer" ,
                                    "Bronchitis" ,
                                    "Cancer" ,
                                    "Cardiovascular disease" ,
                                    "Cervical cancer" ,
                                    "Chest infection" ,
                                    "Chest pain" ,
                                    "Chickenpox" ,
                                    "Chilblains" ,
                                    "Chlamydia" ,
                                    "Chronic kidney disease" ,
                                    "Chronic obstructive pulmonary disease (COPD)" ,
                                    "Chronic pain" ,
                                    "Chronic pancreatitis" ,
                                    "Cirrhosis" ,
                                    "Cold sore" ,
                                    "Common cold" ,
                                    "Common heart conditions" ,
                                    "Conjunctivitis" ,
                                    "Constipation" ,
                                    "Coronavirus (COVID-19)" ,
                                    "Cough" ,
                                    "Crohn's disease" ,
                                    "Cystic fibrosis" ,
                                    "Deep vein thrombosis" ,
                                    "Dehydration" ,
                                    "Dementia" ,
                                    "Depression" ,
                                    "Dermatitis" ,
                                    "Diabetes" ,
                                    "Diarrhea" ,
                                    "Digestive disorder" ,
                                    "Dizziness" ,
                                    "Dry mouth" ,
                                    "Dysphagia (swallowing problems)" ,
                                    "Ear infection" ,
                                    "Earache" ,
                                    "Earwax build-up" ,
                                    "Eating disorders" ,
                                    "Eczema" ,
                                    "End stage liver disease" ,
                                    "End stage renal disease" ,
                                    "Endometriosis" ,
                                    "Enlarged prostate" ,
                                    "Epilepsy" ,
                                    "Erectile dysfunction (impotence)" ,
                                    "Eye cancer" ,
                                    "Eye condition" ,
                                    "Fever" ,
                                    "Fibroids" ,
                                    "Fibromyalgia" ,
                                    "Fluid retention" ,
                                    "Food poisoning" ,
                                    "Fungal nail infection" ,
                                    "Gallbladder cancer" ,
                                    "Gallstones" ,
                                    "Gas" ,
                                    "Gastro-esophageal reflux disease (GERD)" ,
                                    "Gastroenteritis" ,
                                    "General health" ,
                                    "Genetic conditions" ,
                                    "Genital herpes" ,
                                    "Genital symptoms" ,
                                    "Genital warts" ,
                                    "Glaucoma" ,
                                    "Gonorrhoea" ,
                                    "Gout" ,
                                    "Gum disease",
                                    "Hand, foot and mouth disease",
                                    "Hay fever" ,
                                    "Head and neck cancer" ,
                                    "Head lice and nits" ,
                                    "Headache" ,
                                    "Hearing loss" ,
                                    "Heart disease" ,
                                    "Heart Event" ,
                                    "Heart failure" ,
                                    "Heartburn" ,
                                    "Hemorrhoids" ,
                                    "Hepatitis" ,
                                    "High Blood Pressure" ,
                                    "High cholesterol" ,
                                    "HIV/AIDS" ,
                                    "Hodgkin lymphoma" ,
                                    "Hormone replacement therapy (HRT)" ,
                                    "Huntington's disease" ,
                                    "Hyperglycaemia (high blood sugar)" ,
                                    "Hyperthyroidism (overactive thyroid)" ,
                                    "Hypoglycaemia (low blood sugar)",
                                    "Hypothyroidism (underactive thyroid)" ,
                                    "Immunization" ,
                                    "Indigestion" ,
                                    "Infection" ,
                                    "Inflammatory bowel disease (IBD)",
                                    "Influenza (flu)",
                                    "Insomnia" ,
                                    "Iron deficiency anaemia",
                                    "Irritable bowel syndrome (IBS)" ,
                                    "Itching",
                                    "Kidney cancer" ,
                                    "Kidney infection" ,
                                    "Kidney stones" ,
                                    "Lactose intolerance",
                                    "Leg cramps" ,
                                    "Leukaemia" ,
                                    "Lice" ,
                                    "Liver cancer" ,
                                    "Liver disease" ,
                                    "Lung cancer" ,
                                    "Lung disease" ,
                                    "Lupus" ,
                                    "Lyme disease" ,
                                    "Malaria" ,
                                    "Malignant brain tumour (cancerous)",
                                    "Malnutrition" ,
                                    "Measles",
                                    "Memory disorder" ,
                                    "Meningitis" ,
                                    "Menopause" ,
                                    "Mental health condition" ,
                                    "Migraine" ,
                                    "Mood disorder" ,
                                    "Morning sickness" ,
                                    "Mouth cancer" ,
                                    "Mouth ulcer" ,
                                    "Movement disorder" ,
                                    "Multiple myeloma" ,
                                    "Multiple sclerosis (MS)",
                                    "Mumps" ,
                                    "Myasthenia gravis",
                                    "Nausea",
                                    "Nerve pain",
                                    "Neurological Condition",
                                    "Non-Hodgkin lymphoma",
                                    "Nosebleed",
                                    "Obesity" ,
                                    "Obsessive compulsive disorder (OCD)" ,
                                    "Obstructive sleep apnoea" ,
                                    "Osteoporosis" ,
                                    "Otitis externa" ,
                                    "Ovarian cancer" ,
                                    "Ovarian cyst" ,
                                    "Pain" ,
                                    "Pancreatic cancer" ,
                                    "Pancreatitis" ,
                                    "Panic disorder" ,
                                    "Parkinson's disease" ,
                                    "Pelvic inflammatory disease" ,
                                    "Peripheral neuropathy" ,
                                    "Peripheral vascular disease" ,
                                    "Personality disorder" ,
                                    "Post-traumatic stress disorder (PTSD)" ,
                                    "Pregnancy" ,
                                    "Pressure ulcers" ,
                                    "Prostate cancer" ,
                                    "Psoriasis" ,
                                    "Psoriatic arthritis" ,
                                    "Psychosis" ,
                                    "Restless legs syndrome" ,
                                    "Rheumatoid arthritis" ,
                                    "Ringworm and other fungal infections" ,
                                    "Rosacea" ,
                                    "Scabies" ,
                                    "Schizophrenia" ,
                                    "Seizures" ,
                                    "Sexual dysfunction" ,
                                    "Sexually transmitted infections (STIs)" ,
                                    "Shingles" ,
                                    "Shortness of breath" ,
                                    "Sickle cell disease" ,
                                    "Sinusitis" ,
                                    "Skin cancer" ,
                                    "Skin condition" ,
                                    "Sleep disorder" ,
                                    "Sore throat" ,
                                    "Staph (Staphylococcus aureus)" ,
                                    "Stomach ache and abdominal pain" ,
                                    "Stomach cancer" ,
                                    "Stomach ulcer" ,
                                    "Stress" ,
                                    "Stroke" ,
                                    "Sunburn" ,
                                    "Syphilis" ,
                                    "Testicular cancer" ,
                                    "Thrush" ,
                                    "Thyroid cancer" ,
                                    "Thyroid disorder" ,
                                    "Tinnitus" ,
                                    "Tobacco cessation" ,
                                    "Tonsillitis" ,
                                    "Tooth decay" ,
                                    "Toothache" ,
                                    "Transient ischaemic attack (TIA)" ,
                                    "Type 1 diabetes" ,
                                    "Type 2 diabetes" ,
                                    "Ulcerative colitis" ,
                                    "Urinary incontinence" ,
                                    "Urinary tract infection (UTI)" ,
                                    "Urticaria (hives)" ,
                                    "Vaginal discharge" ,
                                    "Vertigo",
                                    "Viruse Infection" ,
                                    "Vitamin B12 or folate deficiency anaemia" ,
                                    "Vomiting" ,
                                    "Warts" ,
                                    "Weight loss" ,
                                    "Weight management" ,
                                    "Wheezing" ,
                                    "Whooping cough",
                    }); 
        }
    }

}
